[package]
name = "furnace-rs-example-posts-crud"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]

[dependencies]
furnace-rs = { path = "../../crates/furnace-rs", version = "=0.9.2", default-features = false, features = ["http", "runtime-tokio"] }
furnace-rs-persistence = { path = "../../crates/furnace-rs-persistence", version = "=0.9.2", features = ["sea-orm-postgres"] }
sea-orm = { version = "=2.0.0", default-features = false, features = ["macros", "sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1", features = ["derive"] }
