[package]
name = "furnace-rs-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
description = "Command-line tools for furnace-rs applications"

[dependencies]
cargo_metadata.workspace = true
furnace = { package = "furnace-rs", path = "../furnace-rs", version = "=1.0.0" }
furnace-rs-common = { path = "../furnace-rs-common", version = "=1.0.0", default-features = false, features = ["http"] }
notify.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
tempfile = "3"
tokio.workspace = true
rustix.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[[bin]]
name = "furnace"
path = "src/main.rs"
doc = false

[lints]
workspace = true
