[package]
name = "furnace-rs-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
description = "HTTP, JWT, cookies, and Passport integrations for furnace-rs"

[features]
default = ["http"]
http = [
    "dep:chrono",
    "dep:axum",
    "dep:axum-extra",
    "dep:hyper",
    "dep:hyper-util",
    "dep:furnace-rs-common-macros",
    "dep:rustix",
    "dep:serde",
    "dep:serde_json",
    "dep:serde_path_to_error",
    "dep:serde_urlencoded",
    "dep:tokio",
    "dep:tower",
    "dep:tower-http",
]
jwt = [
    "dep:base64",
    "dep:jsonwebtoken",
    "dep:serde",
    "dep:serde_json",
    "furnace-rs-common-macros?/passport",
]
cookies = ["http", "dep:cookie", "axum-extra/cookie", "furnace-rs-common-macros?/cookies"]
logger = ["dep:chrono"]
sea-orm = ["http", "dep:sea-orm"]

[dependencies]
axum = { workspace = true, optional = true }
axum-extra = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
hyper-util = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
cookie = { workspace = true, optional = true }
jsonwebtoken = { workspace = true, optional = true }
furnace-rs-common-macros = { path = "../furnace-rs-common-macros", version = "=1.0.1", optional = true }
furnace-rs-core = { path = "../furnace-rs-core", version = "=1.0.1" }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde_path_to_error = { workspace = true, optional = true }
serde_urlencoded = { workspace = true, optional = true }
sea-orm = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tower = { workspace = true, optional = true }
tower-http = { workspace = true, optional = true }
chrono = { version = "0.4.24", optional = true }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
rustix = { workspace = true, optional = true }

[dev-dependencies]
http-body.workspace = true
hyper = { workspace = true, features = ["client", "http2"] }
tempfile = "3"
tokio.workspace = true

[lints]
workspace = true
