[package]
name = "furnace-rs-extra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
description = "Extension boundary for optional furnace-rs framework capabilities"

[dependencies]
furnace-rs-core = { path = "../furnace-rs-core", version = "=0.9.2" }

[lints]
workspace = true
