[package]
name = "furnace-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
description = "Modular Rust application framework with Axum and Passport integrations"

[dependencies]
furnace-rs-common = { path = "../furnace-rs-common", version = "=1.0.0", optional = true, default-features = false }
furnace-rs-core = { path = "../furnace-rs-core", version = "=1.0.0" }
furnace-rs-extra = { path = "../furnace-rs-extra", version = "=1.0.0", optional = true }

[dev-dependencies]
furnace-rs-testing = { path = "../furnace-rs-testing", version = "=1.0.0" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
trybuild.workspace = true

[features]
default = ["common", "runtime-tokio"]
common = ["http", "logger"]
http = ["dep:furnace-rs-common", "furnace-rs-common/http"]
jwt = ["dep:furnace-rs-common", "furnace-rs-common/jwt"]
cookies = ["http", "furnace-rs-common/cookies"]
logger = ["dep:furnace-rs-common", "furnace-rs-common/logger"]
runtime-tokio = ["furnace-rs-core/runtime-tokio"]
extra = ["dep:furnace-rs-extra"]

[lints]
workspace = true
